# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tunnel Tunnel
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Tunnel Tunnel est un espace d’art indépendant situé au centre de Lausanne. La programmation est assurée par un collectif constitué de Sophie Ballmer, Tiphanie Blanc, Olivia Fahmy, Anne-Sylvie Henchoz et Guillaume Pilet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username: charlesechap
timezone: Europe/Zurich
language_default: 'fr'
collections:
  posts:
    output: true
    permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "expos"
      type: "posts" # a collection in your site, in plural form
    values:
      layout: "expo"

flickr:
  cache_dir:       "./_cache/flickr"
  api_key:          edfac20f6422216a30ce56359714910a
  shared_secret:    e5e940256c041580
  access_token:     72157679423020804-987ee22dfd765f2a
  access_secret:    d1354eeafabb3566

# Build settings
markdown: kramdown
theme: minima
gems:
 - jekyll-feed
 - fleakr
 # - flickraw
 - flickr
 # - indii-jekyll-flickr
exclude:
 - Gemfile
 - Gemfile.lock
port: 8080

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: 'http://charlesechap.github.io/site/'
  metadata:
    _posts/expos:
    - name: "layout"
      field:
        element: "hidden"
        value: "expo"
